trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

resources:
  repositories:
    - repository: templates
      type: github
      name: xoac/rust-azure-pipelines
      ref: refs/heads/develop ## TODO you may want to change it to refs/tags/TAG_NAME.
      endpoint: PipelinesTemplates

jobs:
# Cargo check
- template: ci/jobs/cargo-check.yml@templates
  parameters:
    name: check_stable
    displayName: Cargo check stable
    rust: stable
    all: true
    benches: true

- template: ci/jobs/cargo-check.yml@templates
  parameters:
    name: check_nightly
    displayName: Cargo check nightly
    rust: nightly
    all: true

# Check formating
- template: ci/jobs/rustfmt.yml@templates

# Clippy
- template: ci/jobs/cargo-clippy.yml@templates
  parameters:
    all: true

# Cargo test
- template: ci/jobs/cargo-test.yaml@templates
  parameters:
    test-flags:
      nocapture: true
  # Uncomment to overvrite strategy to test only on Windows
  # strategy:
  #   matrix:
  #     Windows:
  #       vmImage: vs2017-win2016


################
# Test stage   #
###############

# Test stable
# - template: ci/test.yml@templates
#   parameters:
#     dependsOn:
#       - cargo_check
#     name: cargo_test_stable
#     displayName: Cargo test
#     cross: true # Test on Windows and macOS
# 
# # Test nightly
# - template: ci/test.yml@templates
#   parameters:
#     name: cargo_test_nightly
#     displayName: Cargo test
#     rust_version: nightly
# 
 # Test cross
 # List of supported targets is available here: https://github.com/rust-embedded/cross#supported-targets
- template: ci/jobs/cargo-cross.yml@templates
  parameters:
   name: cargo_cross
   displayName: Cross check and test
   rust: stable # You can specify here beta nightly or even 1.31
   check_targets:
     - i686-unknown-freebsd
     # - thumbv7em-none-eabihf # bare metal require no_std! future enabled.
   test_targets:
     - mips-unknown-linux-gnu
     - armv7-unknown-linux-musleabihf
     - x86_64-unknown-linux-gnu

###################
#    DEPLOY PART  #
###################
# TODO you need to modify git parameters and specify variable in pipeline. See [README.md](https://github.com/xoac/rust-azure-pipelines/blob/master/README.md)

# Deploy doc
# - template: ci/github-deploy-doc.yml@templates
#   parameters:
#     name: github_deploy_doc
#     dependsOn:
#       - cargo_test_stable
#       - cargo_check
#       - cargo_cross
#     github:
#      user: xoac
#      email: sylwesterrapala@outlook.com
#      repo: https://github.com/xoac/rust-azure-pipelines/
# 
# # Release binary
# - template: ci/github-release.yml@templates
#   parameters:
#    name: github_release
#    dependsOn:
#       - minrust
#       - rustfmt
#       - cargo_check
#       - cargo_test_stable
#       - cargo_cross
#    rust_version: stable
#    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
#    contents: |
#      *
#      !*.rlib
#      !*.d
#      !.*
#    targets: # TODO specify targets you want to release
#     - x86_64-unknown-linux-gnu
#     - x86_64-pc-windows-gnu
#     - x86_64-pc-windows-msvc
#     - x86_64-apple-darwin
#    github:
#     gitHubConnection: PipelinesTemplates # TODO githubConnection that allow you write to repo.
#     repositoryName: xoac/rust-azure-pipelines
#     isPreRelease: true
