trigger: ["master"]
pr: ["master"]

resources:
  repositories:
    - repository: templates
      type: github
      name: xoac/rust-azure-pipelines
      endpoint: PiplinesTemplate


jobs:
# Check formatting
- template: ci/rustfmt.yml@templates
  parameters:
    name: rustfmt

# Test crate
- template: ci/test-stable.yml@templates
  parameters:
    name: test_tokio
    displayName: Test tokio
    cross: true # Test on Windows and macOS

# Cargo check
- template: ci/cargo-check.yml@templates
  parameters:
    name: check
    displayName: Cargo check
    rust: stable

# Try cross compiling
- template: ci/cargo-check-docker.yml@templates
  parameters:
    name: Cross armv7
    container: messense/rust-musl-cross:armv7-musleabihf

# This represents the minimum Rust version supported.
# Tests are not run as tests may require newer versions of rust.
- template: ci/check-minrust.yml@templates
  parameters:
    name: minrust
    rust_version: 1.31.0 # The 2018 edition
