[package]
name = "rust-azure-pipelines"
version = "0.0.1-c"
authors = ["Sylwester Rąpała <sylwesterrapala@outlook.com>"]
edition = "2018"
description = "This is just example hello-world crate to test azure pipelines with rust. You will not find anything useful here"

[dependencies]
