parameters:
  checks: []
  tests: []

# Cross check
# List of supported targets is available here: https://github.com/rust-embedded/cross#supported-targets
jobs:
- ${{ each check in parameters['checks'] }}:
  - template: ../jobs/cross-check.yml
    parameters:
      job_name: cargo_check_${{ check.name }}
      job_displayName: Check target ${{ check.target }} (cross)
      target: ${{ check.target }}

# Cross test 
# List of supported targets is available here: https://github.com/rust-embedded/cross#supported-targets
- ${{ each test in parameters['tests'] }}:
  - template: ../jobs/cross-test.yml
    parameters:
      job_name: cargo_test_${{ test.name }}
      job_displayName: Test target ${{ test.target }} (cross)
      target: ${{ test.target }}
