parameters:
  min_rust_supported: 1.31  # First version of Rust 2018 edition

jobs:
- template: ../jobs/cargo-check.yml
  parameters:
    job_name: check_stable
    job_displayName: Cargo check (stable)
    all: true
    benches: true

- template: ../jobs/cargo-check.yml
  parameters:
    # all azure job parameters start with `job_` prefix
    job_name: check_nightly
    job_displayName: Cargo check (nightly)
    # parameters from running program are with the same name without any prefix
    rust: nightly
    all: true
    benches: true

# Check formating
- template: ../jobs/rustfmt.yml

# Cargo test min rust version
- template: ../jobs/cargo-test.yaml
  parameters:
    job_name: cargo_test_min_ver
    job_displayName: Test min supported version
    test-flags: 
      nocapture: true
    rust: ${{ parameters['min_rust_supported'] }}

# Cargo test last stable version of rust
- template: ../jobs/cargo-test.yaml
  parameters:
    test-flags:
      nocapture: true

# Clippy
- template: ../jobs/cargo-clippy.yml
  parameters:
    all: true
