parameters:
  rust: stable
  benches: false
  release: true

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: ../task/install-rust.yml
    parameters:
      toolchain: ${{ parameters.rust }}

  variables:
    - ${{ if parameters.release }}
    release: "--release"

  - script: |
    set -e
    cargo check ${{ variables.release }} 
    displayName: Check features

  - ${{ if parameters.benches }}:
    - script: cargo check ${{variables.release }} --benches
      displayName: Check benchmarks
