parameters:
  job:                        # Job control parameters 
    name: cargo_check         # Job name
    pre-steps: []             # pre-steps are  called after job steps
    post-steps: []            # post-steps are called before job steps
    # all other job prameters excluding `steps` are supported.
    # Link: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#specifying-jobs

  # global parameters
  rust: stable                # Version of rust. Could be [stable, beta, nightly, 1.31, nightly-2018-08-01 ... ]

  direct-call: "--help"

jobs:
  - job: ${{ coalesce(parameters.job['name'], 'cargo_check') }}
    displayName: ${{ coalesce(parameters.job['displayName'], 'Cargo called directly') }}
    ${{ if parameters.job['pool'] }}:
      pool: ${{ parameters.job['pool'] }}
    ${{ if not(parameters.job['pool']) }}:
      pool:
        vmImage: ubuntu-16.04
    ${{ each item in parameters['job'] }}:
      ${{ if notIn(item.key, 'name', 'displayName', 'pool') }}:
        ${{ item.key }}: ${{item.value}}

    steps:
    - ${{ if parameters.job['pre-steps'] }}:
      - ${{parameters.job['pre-steps'] }}

    - script: cargo ${{ parameters['direct-call'] }}
      displayName: Call cargo direct

    - ${{ if parameters.job['post-steps'] }}:
      - ${{ parameters.job['post-steps'] }}

