parameters:
  rust: stable
  # parameters from cargo check --help
  release: true
  package: ['package1', 'package2']
  exclude: []
  lib: false 
  bin: ''
  bins: false
  example: []
  examples: false
  test: []
  tests: false 

  benches: false

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ubuntu-16.04
  variables:
    cliflags: check
  steps:
  - template: ../steps/install-rust.yml
    parameters:
      toolchain: ${{ parameters.rust }}
 
  - script: echo '##vso[task.setvariable variable=cliflags]$(cliflags) --release'
    enabled: ${{ parameters.release}}
    displayName: "Set using release mode"

  - ${{ each pkg in parameters.package }}
    - script: echo '##vso[task.setvariable variable=cliflags]$(cliflags) --package ${{ pkg }}'
      displayName: "Add package to check '${{ pkg }}'"


  - script: echo $(cliflags)

    #   - script: |
    #     set -e
    #     cargo check $[ variables.release ]
    #     displayName: Check features
    # 
    #   - ${{ if parameters.benches }}:
    #     - script: cargo check ${{variables.release }} --benches
    #       displayName: Check benchmarks
