jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ubuntu-16.04
  container: ${{ parameters.container }}
  steps:
  - script: |
      pwd
      ls
      uname -a
      echo $PATH
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      echo $PATH
      cargo check --all 
    displayName: Check source

  - script: cargo check --tests --all 
    displayName: Check tests
