parameters:
  rust_version: stable

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install-rust.yml

  - script: cargo build --release

  - task: GitHubRelease@0
    displayName: Create realese
    inputs:
      gitHubConnection: PipelinesTemplates
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
      action: create
      repositoryName: xoac/rust-azure-pipelines

