parameters:
  rust_version: stable

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install-rust.yml

  - script: cargo build --release
    displayName: Build create in realese mode
 
  - bash: |
      MY_TAG="$(Build.SourceBranch)"
      MY_TAG=${MY_TAG#refs/tags/}
      echo $MY_TAG
      echo "##vso[task.setvariable variable=build.my_tag]$MY_TAG"
    displayName: "Create tag variable"


  - task: GitHubRelease@0
    displayName: Create realese
    inputs:
      gitHubConnection: PipelinesTemplates
      tagSource: manual
      tag: '$(build.my_tag)'
      action: edit
      repositoryName: xoac/rust-azure-pipelines

