parameters:
  rust_version: stable

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install-rust.yml

  - script: cargo install tomlcli
    displayName: Instll toml CLI

  - script: cargo build --release
    displayName: Build create in realese mode

  - script: |
          tagVersion=$(toml --nocolor Cargo.toml package.version | sed -e 's/^"//' -e 's/"$//')
          echo $tagVersion
    displayName: Get create version

  - task: GitHubRelease@0
    displayName: Create realese
    inputs:
      gitHubConnection: PipelinesTemplates
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
      tagSource: auto
      action: create
      repositoryName: xoac/rust-azure-pipelines

